development:
  fluent_host:   fluentd
  fluent_port:   24224
  tag:           'app.logs'
  messages_type: 'string'

test:
  fluent_host:   'http://fluentd'
  fluent_port:   24224
  tag:           'app.logs'
  messages_type: 'string'

production:
  fluent_host:   'http://fluentd'
  fluent_port:   24224
  tag:           'app.logs'
  messages_type: 'string'